RELENG-791 Add pushdeb pool configs
mozilla-releng/k8s-autoscale pull request #124
Opened 2022-06-09 17:46 UTC by hneiva

2022-06-09 18:00 UTC, escapewindow requested changes
Looks good, but let's add the level 1 pool in prod as well.

Also, aiui k8s-autoscale PRs should only land after the pools have been created. So we'll need SOPS, cloudops-infra, scriptworker-scripts all set up and deployed to the `production` and `dev` branches at least once, and then we can land this PR.

2022-06-09 18:06 UTC, hneiva commented on configs/relengworker-prod/config.yml
> +  - worker_type: mozillavpn-3-pushdeb
Maybe have level 1 on nonprod config and level 3 on prod?
Would we be able to use nonprod 1 for staging?

2022-06-09 18:12 UTC, escapewindow commented on configs/relengworker-prod/config.yml
> +  - worker_type: mozillavpn-3-pushdeb
nonprod level 1 is dev, so it only deploys on pushes to the dev branches, and there are no guarantees about the stability of those workers. If we want a pool deployed for PRs and staging releases on push to the production branches with the latest reviewed and deployed code, we'll want a level 1 prod config for dep.

2022-06-09 20:46 UTC, hneiva commented
Linked PR: https://github.com/mozilla-services/cloudops-infra/pull/4133

2022-06-10 15:42 UTC, JohanLorenzo approved these changes
LGTM! Thanks for adding the prod level-1 for regular staging releases 👍

2023-04-25 11:44 UTC, jcristau commented
AIUI we can close this, beetmover handles these tasks now.

2023-04-25 11:44 UTC, closed without merging